services:
  app:
    build:
      context: .
      target: dev
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .git/
            - .llm/
